AWSTemplateFormatVersion: '2010-09-09'
Description: Pick6 College Football - Cost Monitoring and Budgets

Parameters:
  BudgetLimit:
    Type: Number
    Default: 50
    Description: Monthly budget limit in USD
  
  AlertEmail:
    Type: String
    Description: Email address for budget alerts
    Default: "your-email@example.com"

Metadata:
  Tags:
    Project: Pick6-CollegeFootball
    Version: "2025"
    Environment: shared
    ManagedBy: CloudFormation
    Repository: https://github.com/mmacknight/college-football-pick6
    CostCenter: Pick6-Monitoring

Resources:
  # Budget for monthly spending
  MonthlyBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: "Pick6-Monthly-Budget"
        BudgetLimit:
          Amount: !Ref BudgetLimit
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
        CostFilters:
          Service:
            - Amazon Simple Storage Service
            - AWS Lambda
            - Amazon API Gateway
            - Amazon CloudFront
            - Amazon Route 53
            - Amazon DynamoDB
        CalculatedSpend:
          ActualSpend:
            Amount: 0
            Unit: USD
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlertEmail
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlertEmail

  # CloudWatch Dashboard for monitoring
  Pick6Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: "Pick6-Monitoring"
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", { "stat": "Sum" } ],
                  [ ".", "Duration", { "stat": "Average" } ],
                  [ ".", "Errors", { "stat": "Sum" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Lambda Performance",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/ApiGateway", "Count", { "stat": "Sum" } ],
                  [ ".", "Latency", { "stat": "Average" } ],
                  [ ".", "4XXError", { "stat": "Sum" } ],
                  [ ".", "5XXError", { "stat": "Sum" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "API Gateway Performance",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/CloudFront", "Requests", { "stat": "Sum" } ],
                  [ ".", "BytesDownloaded", { "stat": "Sum" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "us-east-1",
                "title": "CloudFront Usage",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/DynamoDB", "ConsumedReadCapacityUnits", { "stat": "Sum" } ],
                  [ ".", "ConsumedWriteCapacityUnits", { "stat": "Sum" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "DynamoDB Usage",
                "period": 300
              }
            }
          ]
        }

  # Alarm for high Lambda errors
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "Pick6-Lambda-Errors"
      AlarmDescription: "Alert when Lambda functions have high error rate"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref ErrorTopic

  # Alarm for high API Gateway latency
  ApiGatewayLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "Pick6-API-Latency"
      AlarmDescription: "Alert when API Gateway latency is high"
      MetricName: Latency
      Namespace: AWS/ApiGateway
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 5000  # 5 seconds
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref ErrorTopic

  # SNS Topic for error notifications
  ErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "Pick6-Errors"
      Subscription:
        - Protocol: email
          Endpoint: !Ref AlertEmail

Outputs:
  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${Pick6Dashboard}"
  
  BudgetName:
    Description: Budget name for tracking
    Value: !Ref MonthlyBudget
